### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by sandersfrank** [vidar808/Chess-UCI-Server_Droidfish#1]
1) In the zip file was no requirements.txt file, so pip install was not possible

2) Changeing the different path and starting I get the following:

C:\Users\Helmut\Downloads\Chess-UCI-Server_Droidfish-main\Chess-UCI-Server_Droidfish-main>ChessServer.exe
Traceback (most recent call last):
  File "chess.py", line 12, in <module>
    config = json.load(f)
             ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 36 column 3 (char 834)
[5180] Failed to execute script 'chess' due to unhandled exception!

Whats wrong?

**Comment by vidar808** [comment]
Please try the revised version. config.json file needs to be in the same directory as the ChessServer.exe
The chess engine path needs to be set in config.json

  "engines": {
    "Stockfish": {
      "path": "C:\\Users\\administrator\\Desktop\\chess\\stockfish 16\\stockfish-windows-x86-64-avx2.exe",
      "port": 9998
    }
  }
  
  Your router will need port forwarding to allow communication from the remote chess GUI and the chess engine.
  The example config.json shows more detailed options that can be set as an example, while the included one is set for just one chess engine, currently stockfish.
